swagger: "2.0"
info:
  version: "0.0.1"
  title: Node.js mentoring
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /api/users/:
    # binds a127 app logic to a route
    x-swagger-router-controller: getUsers
    get:
      description: Returns 'getUsers' to the caller
      # used as the method name of the controller
      operationId: getUsers
      parameters:
        - name: X-access-token
          in: header
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/UserItem"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  UserItem:
    type: object
    required:
      - name
      - password
    properties:
      refreshToken:
        type: string
        format: uuid
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      token:
        type: string
        format: uuid
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      name:
        type: string
        example: Admin
      email:
        type: string
        example: address@gmail.com
      password:
        type: string
        example: admin
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
